# Copyright (c) 2018, cPanel, LLC.
# All rights reserved.
# http://cpanel.net
#
# This is free software; you can redistribute it and/or modify it under the
# same terms as Perl itself. See L<perlartistic>.

package Char::Replace;

use strict;
use warnings;

# ABSTRACT: Perl naive XS character replacement as an alternate to substitute or transliterate


BEGIN {

    # VERSION: generated by DZP::OurPkgVersion

    require XSLoader;
    XSLoader::load(__PACKAGE__);
}

sub identity_map {
    my $MAP = [];
    $MAP->[ $_ ] = chr($_) for 0..255;
    return $MAP; 
}

sub build_map {
    my (%pairs) = @_;
    my $MAP = identity_map();
    for my $from ( keys %pairs ) {
        length($from) == 1
            or do { require Carp; Carp::croak("build_map: key must be a single character, got '$from'") };
        $MAP->[ ord($from) ] = $pairs{$from};
    }
    return $MAP;
}

1;

=pod

=encoding utf-8

=head1 SYNOPSIS

Char::Replace sample usage

# EXAMPLE: examples/synopsis.pl

=head1 DESCRIPTION

Char::Replace provides XS-accelerated character-level string operations as
an alternative to Perl's C<tr///> and C<s///> operators. All core functions
are implemented in C for maximum performance.

For simple 1:1 character maps, C<replace()> uses a precomputed 256-byte
lookup table (fast path) that avoids per-character type dispatch entirely,
making it roughly 2x faster than C<tr///>. When map entries include
multi-character expansions, deletions, or code ref callbacks, it falls back
to a general path that handles all cases.

=over

=item B<replace> — transliterate one or more ASCII characters. Supports
single-char, multi-char expansion, deletion (empty string), integer
ordinals (IV), and code ref callbacks.

=item B<replace_inplace> — fast in-place 1:1 byte replacement with no
allocation. Up to 3.5x faster than C<replace()> for long strings when only
single-byte substitutions are needed.

=item B<replace_list> — batch replacement across an array of strings (map
built once).

=item B<trim> / B<trim_inplace> — strip leading and trailing whitespace.

=item B<identity_map> / B<build_map> — convenient helpers for constructing
replacement maps.

=back

B<UTF-8 safe:> multi-byte sequences (bytes E<gt>= 0x80) are copied through
unchanged; the map is applied to ASCII bytes only.

B<Taint safe:> the taint flag is propagated from input to output.

=head1 Available functions

=head2 $output = replace( $string, $MAP )

Return a new string '$output' using the replacement map provided by $MAP (Array Ref).
Map entries can be:

=over

=item a string (PV) — replaces the character with that string

=item an empty string — deletes the character from the output

=item an integer (IV) — replaces the character with C<chr(value)> (0–255)

=item undef — keeps the original character unchanged

=item a code ref — called with the character as argument; return value is the replacement
(return undef to keep original, empty string to delete)

B<Note:> Code ref callbacks are significantly slower than static replacements due to
function call overhead. Avoid heavy computation inside callbacks. Callbacks receive
a single-character string argument; for tainted input, the output string inherits the
taint flag from the input (not from the callback return value).

=back

view L</SYNOPSIS> or example just after.

Setting a map entry to an empty string deletes the character from the output:

    $map->[ ord('x') ] = q[];    # delete 'x'
    Char::Replace::replace( "fox", $map ) eq "fo" or die;

Setting a map entry to an integer replaces the character with chr(value):

    $map->[ ord('a') ] = ord('A');  # replace 'a' with 'A'
    Char::Replace::replace( "abc", $map ) eq "Abc" or die;

Setting a map entry to a code ref enables dynamic replacement:

    $map->[ ord('a') ] = sub { uc $_[0] };  # uppercase callback
    Char::Replace::replace( "abc", $map ) eq "Abc" or die;

    # stateful callback
    my $n = 0;
    $map->[ ord('x') ] = sub { ++$n };
    Char::Replace::replace( "xyx", $map ) eq "1y2" or die;

=head2 $map = identity_map()

This is a convenient helper to initialize an ASCII mapping.
It returns an Array Ref, where every character will map to itself by default.

You can then adjust one or several characters.

    my $map = Char::Replace::identity_map();
    $map->[ ord('a') ] = q[XYZ]; # replace 'a' by 'XYZ'

    # replaces all 'a' by 'XYZ'
    Char::Replace::replace( "abcdabcd", $map ) eq "XYZbcdXYZbcd" or die;

=head2 $map = build_map( char => replacement, ... )

Convenience constructor: takes a hash of single-character keys and their
replacement values, and returns an array ref suitable for C<replace()> or
C<replace_inplace()>. Starts from an identity map, so unmapped characters
pass through unchanged.

    my $map = Char::Replace::build_map(
        'a' => 'AA',
        'd' => '',       # delete
        'x' => ord('X'), # IV
        'z' => sub { uc $_[0] },  # callback
    );
    Char::Replace::replace( "abxd", $map ) eq "AAbX" or die;

Croaks if any key is not exactly one character.

=head2 $count = replace_inplace( $string, $MAP )

Modifies C<$string> in place, applying 1:1 byte replacements from C<$MAP>.
Returns the number of bytes actually changed.

Unlike C<replace()>, this function does B<not> allocate a new string — it
modifies the existing SV buffer directly. This makes it significantly faster
(up to 3.5x for long strings) but restricts map entries to single-character
replacements only:

=over

=item a single-character string (PV of length 1)

=item an integer (IV) in range 0–255

=item undef — keeps the original character unchanged

=back

Multi-character strings, empty strings (deletion), and code refs will cause a croak.
Use C<replace()> when you need expansion, deletion, or dynamic callbacks.

    my $map = Char::Replace::identity_map();
    $map->[ ord('a') ] = 'A';

    my $str = "abcabc";
    my $n = Char::Replace::replace_inplace( $str, $map );
    # $str is now "AbcAbc", $n is 2

UTF-8 safety applies: multi-byte sequences are skipped, only ASCII bytes
are eligible for replacement.

=head2 @results = replace_list( \@strings, $MAP )

Batch version of C<replace()>: applies the same replacement map to every
string in the input array. Returns a list of replaced strings.

    my $map = Char::Replace::build_map( 'a' => 'X', 'b' => 'Y' );
    my @results = Char::Replace::replace_list( \@strings, $map );

This is more efficient than calling C<replace()> in a loop because the
replacement map is analysed once and reused across all strings. When the
map is eligible for the fast path (1:1 byte replacements), the 256-byte
lookup table is built once instead of per call.

Input elements that are C<undef> or references produce C<undef> in the
output. Numeric values are coerced to strings.

Croaks if the first argument is not an array reference.

=head2 $string = trim( $string )

=head2 $string = trim( $string, $chars )

Removes leading and trailing characters from a string and returns a new string.

When called with a single argument, removes the default whitespace characters:
C<' '>, C<'\r'>, C<'\n'>, C<'\t'>, C<'\f'>, C<'\v'>.

When called with a second argument C<$chars>, only removes characters present
in that string. Each byte in C<$chars> is treated as a character to trim.
An empty C<$chars> string means "trim nothing".

    Char::Replace::trim("  hello  ")           eq "hello"    or die;
    Char::Replace::trim("xxhelloxx", "x")      eq "hello"    or die;
    Char::Replace::trim("..a.b.c..", ".")      eq "a.b.c"    or die;
    Char::Replace::trim("00123400", "0")       eq "1234"     or die;
    Char::Replace::trim("xyhelloyx", "xy")     eq "hello"    or die;

The UTF-8 state of the string is preserved. Only ASCII bytes are eligible
for trimming; multi-byte UTF-8 sequences are never affected.

=head2 $count = trim_inplace( $string )

=head2 $count = trim_inplace( $string, $chars )

Modifies C<$string> in place, removing leading and trailing characters.
Returns the total number of bytes removed.

When called with a single argument, removes the default whitespace characters
(same set as C<trim()>). When called with C<$chars>, only removes characters
present in that string.

Unlike C<trim()>, this function does B<not> allocate a new string — it
modifies the existing SV buffer directly. Uses C<sv_chop()> internally for
efficient leading-character removal.

    my $str = "  hello world  ";
    my $n = Char::Replace::trim_inplace( $str );
    # $str is now "hello world", $n is 4

    my $csv = ",,value,,";
    my $n2 = Char::Replace::trim_inplace( $csv, "," );
    # $csv is now "value", $n2 is 4

The UTF-8 state of the string is preserved.

=head1 Benchmarks

=head2 char_replace

# EXAMPLE: examples/benchmark-replace.pl

=head2 fast path vs replace_inplace

# EXAMPLE: examples/benchmark-fastpath.pl

=head2 trim

# EXAMPLE: examples/benchmark-trim.pl


=head1 LICENSE

This software is copyright (c) 2018 by cPanel, Inc.

This is free software; you can redistribute it and/or modify it under the same terms as the Perl 5 programming
language system itself.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY
APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE
SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE
OF THE SOFTWARE IS WITH YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,
REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY
WHO MAY MODIFY AND/OR REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE LIABLE TO YOU FOR DAMAGES,
INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF SUCH HOLDER OR OTHER PARTY HAS
BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

